_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.5
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
col:
    value: 30
lbd:
    value: 10
library:
    value: 0
mu:
    value: 40
